-- auto Generated on 2017-01-05 11:03:14 
-- DROP TABLE IF EXISTS `items`; 
CREATE TABLE items(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'name',
    `price` DECIMAL(14,4) NOT NULL DEFAULT 0 COMMENT 'price',
    `pic` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'pic',
    `detail` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'detail',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'items';
